apiVersion: 1

deleteDatasources:
  - name: InfluxDB-1
    orgId: 1

datasources:
  - name: InfluxDB-1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: jmeter
    secureJsonData:
      token: ${INFLUXDB_TOKEN}